# Get vector objects which are now being applied on map

---
CircleObject[] circles
PolygonObject[] polygons
# Stamp of the latest published map reflecting these shapes
builtin_interfaces/Time map_stamp
