---
name: Call Build and Test Feature Repo

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: botsandus/auto-sandbox/.github/workflows/build_test_feature.yaml@main
    secrets: inherit
